### ISSUE TITLE
Skipping Landscape cards if Next focusable card is too far from current focused view.

### ISSUE THREAD

**Issue by mdrafiwynk** [rubensousa/DpadRecyclerView#274]
STR 
1. Select first card of any row which is protrait.
2. Now move to next card which is landscape and scroll to last item of landscape.
3. Now move to next row which is again portrait and select firs card.
4. Now Press dpad up button two times and go to portrait row again.
5. Now Press dpad down you can observe, focus is going to portrait again and landscape row is skipped. 
Check the sample below. 
Hunch - Focus find the nearest last focused card. If its not found then it skip the next rail and go to third rail card which is nearest than that. 

Note: Issue exist in latest code. Sample created with latest code.

[DpadRecyclerView.zip](https://github.com/user-attachments/files/17284528/DpadRecyclerView.zip)

https://github.com/user-attachments/assets/69365400-bc29-4b2a-a16e-3993667dfc99

**Comment by mdrafiwynk** [comment]
Another one. Not same

**Comment by rubensousa** [comment]
The zip you uploaded doesn't contain the code for the example you shared in the original post. Can you please share that?

**Comment by rubensousa** [comment]
The zip you attached only contains the library original source code and not the sample

**Comment by mdrafiwynk** [comment]
I changed in your sample. I don't have other sample.

**Comment by rubensousa** [comment]
Thanks! That's perfect and I can see the issue there. Will take a look. Can you please do the same for the other issue?

**Comment by mdrafiwynk** [comment]
Sure. I will provide it today later on.

**Comment by rubensousa** [comment]
@mdrafiwynk fix is here: https://github.com/rubensousa/DpadRecyclerView/pull/275

I will add a UI test and verify if everything is good. Looks like the root cause of this issue is similar to the other one you created

**Comment by rubensousa** [comment]
@mdrafiwynk Can you please try the `1.4.0-SNAPSHOT` to confirm the fix solves your issue? Would be great if you could confirm the other issue as well, as they seem related

You will need this in `settings.gradle`:

```groovy
repositories {
    maven {
        url 'https:///s01.oss.sonatype.org/content/repositories/snapshots'
    }
}
```

**Comment by mdrafiwynk** [comment]
Ok. I will and get back to you. Could you please also let me know the change as well so that i can add this in my older version which i used?

**Comment by rubensousa** [comment]
@mdrafiwynk I didn't understand your question. You can't change anything in the client side, the fix is in the library. Or do you want to cherry-pick the change yourself? The fix was done in this class: https://github.com/rubensousa/DpadRecyclerView/blob/master/dpadrecyclerview/src/main/java/com/rubensousa/dpadrecyclerview/layoutmanager/focus/DefaultFocusInterceptor.kt

**Comment by mdrafiwynk** [comment]
Yes i got the change. But i am not using latest version of your library because I am currently not using latest kotlin version. If i use your latest version then i have to remove synthetic and need to use viewbinding which is very big change for me. Could you please create any new version from 1.2.0-alpha03 with new fix for me? if i add this patch i need to add your library as module and change in that class.

**Comment by rubensousa** [comment]
I can downgrade kotlin to the previous version as there's really no need to enforce 2.0 if this breaks other projects

**Comment by rubensousa** [comment]
@mdrafiwynk looks like you would need 1.8.0 or below, `1.2.0-alpha03` uses `1.8.20`. Can't you just enforce kotlin version down using this approach? https://peyrone.medium.com/conflicting-versions-of-kotlins-standard-library-kotlin-stdlib-85c98c7fab2a

I would like to avoid doing fixes for previous versions since they're really old now and don't contain the latest fixes I've been doing in latest versions

**Comment by rubensousa** [comment]
This and similar approaches should work:

```groovy
implementation("com.rubensousa.dpadrecyclerview:dpadrecyclerview:1.4.0-SNAPSHOT") {
    exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib-jdk7'
    exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib-jdk8'
    exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib'
}
```

Can you explain how you managed to use `1.2.0-alpha03` which uses `1.8.20`?

**Comment by rubensousa** [comment]
@mdrafiwynk I just checked and that won't work since internally we're using enums.entries which isn't available in previous versions of kotlin. I think your best approach would be to copy this project as a module to your project and make the adjustments there. You should've moved away from kotlin synthetics 2 years ago :/

**Comment by mdrafiwynk** [comment]
No problem.. Thanks for fixing this issue and your support. 🙏🙏
